---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metric-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  sources:
    - repoURL: 'https://kubernetes-sigs.github.io/metrics-server/'
      chart: metrics-server
      targetRevision: {{ .Values.apps.versions.metallb }}
      helm:
        valueFiles:
          - $values/clusters/xs4/kube/base/metrics-server/values.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.branch }}
      ref: values
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: 'Project:'
      value: "https://github.com/kubernetes-sigs/metrics-server/"