---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: metallb-system
    server: {{ .Values.spec.destination.server }}
  sources:
    - repoURL: 'https://metallb.github.io/metallb'
      chart: metallb
      targetRevision: {{ .Values.apps.versions.metallb }}
      helm:
        valueFiles:
          - $values/clusters/xs4/kube/base/metallb/values.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: HEAD
      ref: values
    - repoURL: {{ .Values.spec.source.repoURL }}
      path: clusters/xs4/kube/base/metallb/addresses
      targetRevision: HEAD
  project: default
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: addresspools.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true