---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: photoprism
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    path: clusters/xs4/kube/media/photoprism
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: photoprism
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true