---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vikunja
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: vikunja
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: kolaente.dev/vikunja
    chart: vikunja
    targetRevision: {{ index .Values.apps.versions "vikunja" }}
    helm:
      valuesObject:
        postgresql:
          enabled: false
        frontend:
          ingress:
            main:
              enabled: false
        typesense:
          enabled: false
        api:
          ingress:
            main:
              enabled: false
          configMaps:
            config:
              enabled: false
              # data:
              #   config.yml:
              #     service:
              #       enableregistration: false
          persistence:
            data:
              enabled: true
              accessMode: ReadWriteOnce
              size: 10Gi
              mountPath: /app/vikunja/files
              storageClass: "replicated"
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
    syncOptions:
    - CreateNamespace=true
  info:
    - name: 'Project:'
      value: "https://vikunja.io/"