---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vikunja
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: vikunja
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: kolaente.dev/vikunja
    chart: vikunja
    targetRevision: {{ index .Values.apps.versions "vikunja" }}
    helm:
      parameters:
        - name: postgresql.enabled
          value: 'false'
        - name: frontend.ingress.main.enabled
          value: 'false'
        - name: typesense.enabled
          value: 'false'
        - name: api.ingress.main.enabled
          value: 'false'
        - name: api.configMaps.config.enabled
          value: 'true'
        - name: api.configMaps.config.data.config.yml.service.enableregistration
          value: 'false'
        - name: api.persistence.data.enabled
          value: 'true'
        - name: api.persistence.data.accessMode
          value: 'ReadWriteOnce'
        - name: api.persistence.data.size
          value: '10Gi'
        - name: api.persistence.data.mountPath
          value: '/app/vikunja/files'
        - name: api.persistence.data.storageClass
          value: 'replicated'
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
    syncOptions:
    - CreateNamespace=true
  info:
    - name: 'Project:'
      value: "https://vikunja.io/"