apiVersion: v1
kind: Secret
metadata:
    name: github-gitops
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
data:
    project: ENC[AES256_GCM,data:sW2JH4kvW6psULW2,iv:sfaQkacbtEZ/2trg849ungFeLhY7qqOdbGeo8pm/drk=,tag:jxmKLGWCsxaIXp04hMN4tg==,type:str]
    sshPrivateKey: ENC[AES256_GCM,data:EpYeyzWb3KCl8Usa/Ablhbtt4l/08xomGKrnpfDAiDNjFnowkeMX5MQk19Kcv/rft63fNGbluFkYBG09FprHaZ32uvEx6Z2XisLi1XDEIsqSzUJ1qUp76WkAdnii28j7mKxB6ac+DBKgAGYFU9cwZ2rBxuWNt70elJ/h7XYfeXQIpNi8T+HKK7I6cCdMwvEqmGEHDwCx5PIT+QbfuJK4lrExA/jUSDR9xJiCZjMSV8ugIyXe8PPynDziSDrJXZUW2+FEoKkoTSSHCyY5vGZrfzQFmAgewyWpZ+o0vxPEY34QL22vpe6bvMr/bzom0iHmOVZTQJhqBYZloHddz4bE+r6DM+Cp3kwfcVy0Ih9PWgyA7Cv8o7O3y4pb6vd+v8e54KrxdXc3D/KyIGx4y02K9AD+d9s/iDRisCg9fr19kuWk+r350igD5MDiKLOkmQDmJayfDPP67TdsNtl+UkIWqsdpuNa3izv60Na0RGMq/pGuuytNO/kMx3VJpZKMqjaunt26Hhrq3Izn0XJ/wCTkUNQT6niy7ModCZ3XgEbTCsYMjzOyTmEMzADRlbA4qybK7+Hr/4d9eVefIDMGXWKUccfDlMJUix1R9T0b8HxUZjx2oqE5x9juOcrPFX2mlFiA1b44n4l7+1g5swNhwJs0DbyWEQGdilXNLSrSGhMFcXF/mixxGVhk4qPgmKp0wab9AsmTofYGYc0Ux+jY2J4UNuAWZTc=,iv:a4UwTUgZmq7GSsBNsgAbZO/HxLJrYJSqiHXp7YOkzvE=,tag:dNFjbcGgIVwCpMxhbtbnfA==,type:str]
    type: Z2l0
    url: ENC[AES256_GCM,data:dwO01QWjY3Rbeynrf4u7d6ogS3jiSQbyxHakXfSdd8dtQezm1X51okj2VIdw7ilVBSRHRA==,iv:FCZwLZZh6W5rjpN8iMBK5lyx+5deU3NA9iFc3ppdftQ=,tag:zzS0bEmVhQSuuusiFHq2Sw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpts4q4cykrscvel3jwuv6ann3ff9952h3kljy4rancps5h2ag5sjf63pj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWCtVQk50Z3JQNDZCRTNl
            djJNd2pXWGZUTzk1b1lyYVBuaVNnVU9jeTA0Cm9TM0l0VERBeFRpVUdzaVRnOXF2
            MnJNTno2RS9JTFRKcVErRm56SEM5SXcKLS0tIDlVbmNzVk5YWGdWa0ZmRFVOQ3JT
            TGlxQldNS1Q1YkdNQTZxSzFnNkdNMjAKmnOngUJY4boM8zzfJVB5Is+J3wE71K8z
            bP9prRJLzRc1UYdYI2WSKFgh69njkBr+8Q2aILoWwX1c1K1C98GZrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-09T14:45:57Z"
    mac: ENC[AES256_GCM,data:HDWK8Tv/L+0Vb3tWCNIBpDC+FqyLLKNGimDVEAKNJYhePLIYr263pSKU8hWaZvcYn3axxXRFwQUcHUkzOF0nSwTnIgHatkouLj5L1oFhiPSuc132e93FqnE/FbrC1vGdS0dks2c2XJo6d9XmzKEf/yCdx23GrM+ohuCB0eknIdw=,iv:8wji/Umw37hGqAQ3dy7r50gGFfbC6fALwjRlibe/Jw0=,tag:9+EBDC0ntqnATWISwVZBoA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
