---
kind: PersistentVolumeClaim
metadata:
  name: actual-data
  labels:
    app: actual
apiVersion: v1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "replicated"
  resources:
    requests:
      storage: 10Gi