---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-navidrome-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_data/apps/navidrome
    server: 192.168.80.250
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-navidrome-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-navidrome-music
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyOnce
  nfs:
    path: /mnt/nfs_data/media/music
    server: 192.168.80.250
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-navidrome-music
spec:
  accessModes:
    - ReadOnlyOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi