apiService:
  # Specifies whether to skip TLS verification
  insecureSkipTLSVerify: "false"

service:
  type: ClusterIP
  port: 443
  annotations: {}
  labels:
    {
      kubernetes.io/cluster-service: "true",
      kubernetes.io/name: "Metrics-server"
    }