---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs

resources:
- ./namespace.yaml

helmCharts:
- name: openebs
  repo: https://openebs.github.io/openebs
  namespace: openebs
  version: 4.0.1
  includeCRDs: true
  valuesInline:
    openebs:
      engines.local.lvm.enabled: false
      engines.local.zfs.enabled: false
      engines.replicated.mayastor.enabled: false
      lvm-localpv.enabled: false
      lvm-localpv.crds.lvmLocalPv.enabled: false
      openebs-crds.csi.volumeSnapshots.enabled: false
      openebs-crds.csi.volumeSnapshots.keep: false
    
patches:
- path: ./patches/openebs-hostpath.yaml
  target:
    kind: StorageClass
    name: openebs-hostpath