---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs

resources:
- ./namespace.yaml

helmCharts:
- name: openebs
  repo: https://openebs.github.io/openebs
  namespace: openebs
  version: 4.0.1
  includeCRDs: true
  valuesInline:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: true
    lvm-localpv:
      enabled: false
    lvm-localpv:
      crds:
        lvmLocalPv:
          enabled: false
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
          keep: false
patches:
- path: ./patches/openebs-hostpath.yaml
  target:
    kind: StorageClass
    name: openebs-hostpath