---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ./namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.6/manifests/install.yaml
# - ./base/appsforapps.yaml
# - ./base/ingress.yaml

patches:
- path: ./patches/argocd-cm.yaml
  target:
    kind: ConfigMap
    name: argocd-cm
- path: ./patches/argocd-repo-server.yaml
  target:
    kind: Deployment
    name: argocd-repo-server

generators:
  - ./secret-generator.yaml