---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ./namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.13/manifests/install.yaml
- ./appofapps.yaml
- ./ingress.yaml

patches:
- path: ./patches/argocd-cm.yaml
  target:
    kind: ConfigMap
    name: argocd-cm
- path: ./patches/argocd-cmd-params-cm.yaml
  target:
    kind: ConfigMap
    name: argocd-cmd-params-cm
- path: ./patches/argocd-repo-server.yaml
  target:
    kind: Deployment
    name: argocd-repo-server

generators:
  - ./secret-generator.yaml