apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: hyperconverged
spec:
  podTemplate:
    spec:
      initContainers:
        - name: drbd-shutdown-guard
          $patch: delete
        - name: drbd-module-loader
          $patch: delete
      volumes:
        - name: run-systemd-system
          $patch: delete
        - name: run-drbd-shutdown-guard
          $patch: delete
        - name: systemd-bus-socket
          $patch: delete
        - name: lib-modules
          $patch: delete
        - name: usr-src
          $patch: delete
        - name: etc-lvm-backup
          hostPath:
            path: /var/mnt/storage/backup
            type: DirectoryOrCreate
        - name: etc-lvm-archive
          hostPath:
            path: /var/mnt/storage/archive
            type: DirectoryOrCreate
  
  storagePools:
    - name: local
      lvmPool:
        volumeGroup: local
      source:
        hostDevices:
          - /dev/sdb
          